<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-MyModularStore.ReportWorker-70db469e-9aaf-41c7-84eb-37f6c9bd7996</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit.Azure.ServiceBus.Core" Version="8.1.0" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.1.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyModularStore.Shared\MyModularStore.Shared.csproj" />
  </ItemGroup>
</Project>
